import { test }                                      from 'node:test'
import assert                                        from 'node:assert/strict'
import { mkdtempSync, rmSync, writeFileSync }        from 'fs'
import { join }                                      from 'path'
import { tmpdir }                                    from 'os'
import { isManaged }                                 from '../src/check.js'

const MANAGED_HEADER = '# Generated by @avelor/vhost — do not edit'

function tmpDir() {
  return mkdtempSync(join(tmpdir(), 'vhost-check-test-'))
}

// ── isManaged ─────────────────────────────────────────────────────────────────

test('isManaged — returns true for a file with the managed header', () => {
  const dir  = tmpDir()
  const path = join(dir, 'example.com.conf')
  try {
    writeFileSync(path, `${MANAGED_HEADER}\n<VirtualHost *:80>\n</VirtualHost>\n`)
    assert.ok(isManaged(path))
  } finally {
    rmSync(dir, { recursive: true })
  }
})

test('isManaged — returns false for a manually written conf', () => {
  const dir  = tmpDir()
  const path = join(dir, 'manual.conf')
  try {
    writeFileSync(path, `<VirtualHost *:80>\n    ServerName manual.com\n</VirtualHost>\n`)
    assert.ok(!isManaged(path))
  } finally {
    rmSync(dir, { recursive: true })
  }
})

test('isManaged — returns false for an empty file', () => {
  const dir  = tmpDir()
  const path = join(dir, 'empty.conf')
  try {
    writeFileSync(path, '')
    assert.ok(!isManaged(path))
  } finally {
    rmSync(dir, { recursive: true })
  }
})

test('isManaged — returns false for a nonexistent path', () => {
  assert.ok(!isManaged('/nonexistent/path/to.conf'))
})

test('isManaged — partial header prefix does not match', () => {
  const dir  = tmpDir()
  const path = join(dir, 'partial.conf')
  try {
    writeFileSync(path, `# Generated by something-else\n<VirtualHost *:80>\n</VirtualHost>\n`)
    assert.ok(!isManaged(path))
  } finally {
    rmSync(dir, { recursive: true })
  }
})
