import { test } from 'node:test'
import assert   from 'node:assert/strict'
import { staticVhost, proxyVhost, catchallVhost, errorsConf, securityConf } from '../src/templates.js'

// ── staticVhost ───────────────────────────────────────────────────────────────

test('staticVhost — has managed marker on first line', () => {
  const out = staticVhost('example.com', { aliases: [], root: '/var/www', ssl: null })
  assert.ok(out.startsWith('# Generated by @avelor/vhost'))
})

test('staticVhost — generates HTTP redirect block', () => {
  const out = staticVhost('example.com', { aliases: [], root: '/var/www', ssl: null })
  assert.ok(out.includes('<VirtualHost *:80>'))
  assert.ok(out.includes('RewriteRule ^ https://'))
})

test('staticVhost — generates HTTPS block with DocumentRoot', () => {
  const out = staticVhost('example.com', { aliases: [], root: '/var/www/site', ssl: null })
  assert.ok(out.includes('<VirtualHost *:443>'))
  assert.ok(out.includes('DocumentRoot /var/www/site'))
  assert.ok(out.includes('<Directory /var/www/site>'))
})

test('staticVhost — no aliases omits ServerAlias', () => {
  const out = staticVhost('example.com', { aliases: [], root: '/var/www', ssl: null })
  assert.ok(!out.includes('ServerAlias'))
})

test('staticVhost — aliases add ServerAlias and RewriteCond', () => {
  const out = staticVhost('example.com', { aliases: ['www.example.com'], root: '/var/www', ssl: null })
  assert.ok(out.includes('ServerAlias www.example.com'))
  assert.ok(out.includes('RewriteCond %{SERVER_NAME} =www.example.com'))
})

test('staticVhost — certbot placeholder when ssl is null', () => {
  const out = staticVhost('example.com', { aliases: [], root: '/var/www', ssl: null })
  assert.ok(out.includes('# SSL managed by Certbot'))
  assert.ok(!out.includes('SSLEngine on'))
})

test('staticVhost — manual SSL block when ssl is provided', () => {
  const ssl = { cert: '/etc/ssl/cert.pem', key: '/etc/ssl/key.pem' }
  const out = staticVhost('example.com', { aliases: [], root: '/var/www', ssl })
  assert.ok(out.includes('SSLEngine on'))
  assert.ok(out.includes('SSLCertificateFile /etc/ssl/cert.pem'))
  assert.ok(out.includes('SSLCertificateKeyFile /etc/ssl/key.pem'))
  assert.ok(!out.includes('# SSL managed by Certbot'))
})

test('staticVhost — log paths use domain name', () => {
  const out = staticVhost('my.domain.com', { aliases: [], root: '/var/www', ssl: null })
  assert.ok(out.includes('my.domain.com-error.log'))
  assert.ok(out.includes('my.domain.com-access.log'))
})

// ── proxyVhost ────────────────────────────────────────────────────────────────

test('proxyVhost — has managed marker on first line', () => {
  const out = proxyVhost('api.example.com', { aliases: [], port: 3000, ssl: null })
  assert.ok(out.startsWith('# Generated by @avelor/vhost'))
})

test('proxyVhost — generates ProxyPass directives with correct port', () => {
  const out = proxyVhost('api.example.com', { aliases: [], port: 3000, ssl: null })
  assert.ok(out.includes('ProxyPass        / http://localhost:3000/'))
  assert.ok(out.includes('ProxyPassReverse / http://localhost:3000/'))
})

test('proxyVhost — no DocumentRoot', () => {
  const out = proxyVhost('api.example.com', { aliases: [], port: 3000, ssl: null })
  assert.ok(!out.includes('DocumentRoot'))
})

test('proxyVhost — includes ProxyPreserveHost', () => {
  const out = proxyVhost('api.example.com', { aliases: [], port: 3000, ssl: null })
  assert.ok(out.includes('ProxyPreserveHost On'))
})

// ── catchallVhost ─────────────────────────────────────────────────────────────

test('catchallVhost — ServerName is underscore', () => {
  const out = catchallVhost('/var/www/vhost-errors')
  assert.equal(out.match(/ServerName _/g)?.length, 2) // once per VirtualHost
})

test('catchallVhost — uses snakeoil cert for HTTPS', () => {
  const out = catchallVhost('/var/www/vhost-errors')
  assert.ok(out.includes('ssl-cert-snakeoil.pem'))
  assert.ok(out.includes('ssl-cert-snakeoil.key'))
})

test('catchallVhost — MultiViews enabled', () => {
  const out = catchallVhost('/var/www/vhost-errors')
  assert.ok(out.includes('Options +MultiViews'))
})

test('catchallVhost — RewriteRule redirects to /catchall', () => {
  const out = catchallVhost('/var/www/vhost-errors')
  assert.ok(out.includes('RewriteRule ^ /catchall [PT,L]'))
})

test('catchallVhost — uses provided errors dir', () => {
  const out = catchallVhost('/custom/errors/path')
  assert.ok(out.includes('DocumentRoot /custom/errors/path'))
})

// ── errorsConf ────────────────────────────────────────────────────────────────

test('errorsConf — has managed marker on first line', () => {
  const out = errorsConf('/var/www/vhost-errors', [404])
  assert.ok(out.startsWith('# Generated by @avelor/vhost'))
})

test('errorsConf — generates ErrorDocument for each code without extension', () => {
  const out = errorsConf('/var/www/vhost-errors', [404, 500, 503])
  assert.ok(out.includes('ErrorDocument 404 /vhost-errors/404'))
  assert.ok(out.includes('ErrorDocument 500 /vhost-errors/500'))
  assert.ok(out.includes('ErrorDocument 503 /vhost-errors/503'))
})

test('errorsConf — adds JSON, XML and plain text MIME types', () => {
  const out = errorsConf('/var/www/vhost-errors', [404])
  assert.ok(out.includes('AddType application/json .json'))
  assert.ok(out.includes('AddType application/xml  .xml'))
  assert.ok(out.includes('AddType text/plain       .txt'))
})

test('errorsConf — sets X-Powered-By header', () => {
  const out = errorsConf('/var/www/vhost-errors', [404])
  assert.ok(out.includes('Header always set X-Powered-By "avelor/vhost"'))
})

test('errorsConf — Alias points to errors dir', () => {
  const out = errorsConf('/var/www/vhost-errors', [404])
  assert.ok(out.includes('Alias /vhost-errors /var/www/vhost-errors'))
})

// ── securityConf ──────────────────────────────────────────────────────────────

test('securityConf — has managed marker on first line', () => {
  const out = securityConf()
  assert.ok(out.startsWith('# Generated by @avelor/vhost'))
})

test('securityConf — sets ServerTokens to Prod', () => {
  const out = securityConf()
  assert.ok(out.includes('ServerTokens Prod'))
})

test('securityConf — disables ServerSignature', () => {
  const out = securityConf()
  assert.ok(out.includes('ServerSignature Off'))
})

test('securityConf — overrides Server header with vhost', () => {
  const out = securityConf()
  assert.ok(out.includes('Header always set Server'))
  assert.ok(out.includes('"vhost"'))
})

test('securityConf — sets X-Powered-By to avelor/vhost', () => {
  const out = securityConf()
  assert.ok(out.includes('Header always set X-Powered-By'))
  assert.ok(out.includes('"avelor/vhost"'))
})

test('securityConf — sets X-Content-Type-Options to nosniff', () => {
  const out = securityConf()
  assert.ok(out.includes('Header always set X-Content-Type-Options'))
  assert.ok(out.includes('"nosniff"'))
})

test('securityConf — sets X-Frame-Options to SAMEORIGIN', () => {
  const out = securityConf()
  assert.ok(out.includes('Header always set X-Frame-Options'))
  assert.ok(out.includes('"SAMEORIGIN"'))
})

test('securityConf — sets Referrer-Policy', () => {
  const out = securityConf()
  assert.ok(out.includes('Header always set Referrer-Policy'))
  assert.ok(out.includes('"strict-origin-when-cross-origin"'))
})
