import { existsSync, readFileSync } from 'fs'
import { resolve }                  from 'path'
import { loadConfig }               from './config.js'
import { enabledSites, confEnabled, SITES_AVAILABLE, ERRORS_DIR } from './apache.js'
import { ok, warn, fail, dim } from './format.js'

const MANAGED_MARKER   = '# Generated by @avelor/vhost'
const APACHE_INTERNALS = new Set(['000-default', 'default-ssl'])

export function check() {
  let config
  try {
    config = loadConfig()
  } catch (err) {
    console.error(`vhost: ${err.message}`)
    process.exit(1)
  }

  const enabled = new Set(enabledSites())
  const { sites } = config
  let issues = 0

  console.log('')

  // Infrastructure checks
  issues += infra('catch-all',
    enabled.has('000-catchall'),
    'not configured — run: vhost apply')

  issues += infra('vhost-errors.conf',
    confEnabled('vhost-errors'),
    'not active — run: vhost apply')

  issues += infra('error pages',
    existsSync(ERRORS_DIR),
    `${ERRORS_DIR} missing — run: vhost apply`,
    dim(ERRORS_DIR))

  console.log('')

  const allDomains = new Set([
    ...Object.keys(sites),
    ...enabled,
  ])
  const pad = Math.max(...[...allDomains].map(d => d.length), 0)

  // Sites declared in sites.yml
  for (const [domain, cfg] of Object.entries(sites)) {
    const confPath   = resolve(SITES_AVAILABLE, `${domain}.conf`)
    const confExists = existsSync(confPath)
    const isEnabled  = enabled.has(domain)
    const managed    = confExists && isManaged(confPath)
    const detail     = cfg.mode === 'proxy' ? `:${cfg.port}` : cfg.root

    if (!confExists) {
      console.log(fail(`${domain.padEnd(pad)}   not applied → run: vhost apply ${domain}`))
      issues++
    } else if (!isEnabled) {
      console.log(warn(`${domain.padEnd(pad)}   conf exists but not enabled → run: a2ensite ${domain}`))
      issues++
    } else if (!managed) {
      console.log(warn(`${domain.padEnd(pad)}   ${dim('manual config')}   → run: vhost apply ${domain} to migrate`))
      issues++
    } else {
      console.log(ok(`${domain.padEnd(pad)}   ${dim('managed')}   ${dim(detail)}`))
    }
  }

  // Sites enabled in Apache but absent from sites.yml
  for (const name of enabled) {
    if (APACHE_INTERNALS.has(name) || name === '000-catchall') continue
    if (sites[name]) continue

    const confPath = resolve(SITES_AVAILABLE, `${name}.conf`)
    const managed  = existsSync(confPath) && isManaged(confPath)
    const tag      = managed ? dim('managed') : dim('manual config')
    console.log(warn(`${name.padEnd(pad)}   ${tag}   not in sites.yml`))
  }

  console.log('')

  if (issues > 0) {
    console.log(`  \x1b[31m✖\x1b[0m ${issues} issue${issues !== 1 ? 's' : ''} found.\n`)
    process.exit(1)
  } else {
    console.log(`  \x1b[32m✓\x1b[0m all good.\n`)
  }
}

export function isManaged(confPath) {
  try {
    const first = readFileSync(confPath, 'utf8').split('\n')[0]
    return first.startsWith(MANAGED_MARKER)
  } catch {
    return false
  }
}

function infra(label, condition, errorMsg, successSuffix = '') {
  if (condition) {
    console.log(ok(`${label}${successSuffix ? '   ' + successSuffix : ''}`))
    return 0
  }
  console.log(fail(`${label}   ${errorMsg}`))
  return 1
}
