export function staticVhost(domain, cfg) {
  const aliases      = cfg.aliases.length ? `    ServerAlias ${cfg.aliases.join(' ')}\n` : ''
  const allNames     = [domain, ...cfg.aliases]
  const rewriteConds = allNames
    .map((n, i) => `    RewriteCond %{SERVER_NAME} =${n}${i < allNames.length - 1 ? ' [OR]' : ''}`)
    .join('\n')
  const sslBlock = cfg.ssl
    ? `    SSLEngine on\n    SSLCertificateFile ${cfg.ssl.cert}\n    SSLCertificateKeyFile ${cfg.ssl.key}`
    : `    # SSL managed by Certbot`

  return `# Generated by @avelor/vhost — do not edit
<VirtualHost *:80>
    ServerName ${domain}
${aliases}    RewriteEngine on
${rewriteConds}
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:443>
    ServerName ${domain}
${aliases}
    DocumentRoot ${cfg.root}
    <Directory ${cfg.root}>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog  \${APACHE_LOG_DIR}/${domain}-error.log
    CustomLog \${APACHE_LOG_DIR}/${domain}-access.log combined
${sslBlock}
</VirtualHost>
`
}

export function proxyVhost(domain, cfg) {
  const aliases      = cfg.aliases.length ? `    ServerAlias ${cfg.aliases.join(' ')}\n` : ''
  const allNames     = [domain, ...cfg.aliases]
  const rewriteConds = allNames
    .map((n, i) => `    RewriteCond %{SERVER_NAME} =${n}${i < allNames.length - 1 ? ' [OR]' : ''}`)
    .join('\n')
  const sslBlock = cfg.ssl
    ? `    SSLEngine on\n    SSLCertificateFile ${cfg.ssl.cert}\n    SSLCertificateKeyFile ${cfg.ssl.key}`
    : `    # SSL managed by Certbot`

  return `# Generated by @avelor/vhost — do not edit
<VirtualHost *:80>
    ServerName ${domain}
${aliases}    RewriteEngine on
${rewriteConds}
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<VirtualHost *:443>
    ServerName ${domain}
${aliases}
    ProxyPreserveHost On
    ProxyPass        / http://localhost:${cfg.port}/
    ProxyPassReverse / http://localhost:${cfg.port}/

    ErrorLog  \${APACHE_LOG_DIR}/${domain}-error.log
    CustomLog \${APACHE_LOG_DIR}/${domain}-access.log combined
${sslBlock}
</VirtualHost>
`
}

export function catchallVhost(errorsDir) {
  return `# Generated by @avelor/vhost — do not edit
<VirtualHost *:80>
    ServerName _
    DocumentRoot ${errorsDir}
    <Directory ${errorsDir}>
        Options +MultiViews -Indexes
        Require all granted
    </Directory>
    RewriteEngine On
    RewriteRule ^ /catchall [PT,L]
</VirtualHost>

<VirtualHost *:443>
    ServerName _
    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/ssl-cert-snakeoil.pem
    SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key
    DocumentRoot ${errorsDir}
    <Directory ${errorsDir}>
        Options +MultiViews -Indexes
        Require all granted
    </Directory>
    RewriteEngine On
    RewriteRule ^ /catchall [PT,L]
</VirtualHost>
`
}

export function securityConf() {
  return `# Generated by @avelor/vhost — do not edit
ServerTokens Prod
ServerSignature Off
Header always set Server              "vhost"
Header always set X-Powered-By       "avelor/vhost"
Header always set X-Content-Type-Options "nosniff"
Header always set X-Frame-Options    "SAMEORIGIN"
Header always set Referrer-Policy    "strict-origin-when-cross-origin"
`
}

export function errorsConf(errorsDir, errorCodes) {
  const docs = errorCodes.map(c => `ErrorDocument ${c} /vhost-errors/${c}`).join('\n')
  return `# Generated by @avelor/vhost — do not edit
Alias /vhost-errors ${errorsDir}
<Directory ${errorsDir}>
    Options +MultiViews -Indexes
    AddType application/json .json
    AddType application/xml  .xml
    AddType text/plain       .txt
    Header always set X-Powered-By "avelor/vhost"
    Require all granted
</Directory>

${docs}
`
}
